use_frameworks!

target 'ConfettiView_Example' do
  pod 'ConfettiView', :path => '../'

  target 'ConfettiView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
